# config.py

INITIAL_CAPITAL = 10_000.0

TICKERS = ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "META"]

START_DATE = "2022-01-01"
END_DATE = "2024-12-31"

STRATEGY = "HYBRID"


POLYGON_API_KEY = "pXfexlW5Gp_vfwuT1aDRFYFWQjMhmyKc"

TIMESPAN = "day"
MULTIPLIER = 1

CACHE_DIR = "data_cache"
USE_CACHE = True
